### ISSUE TITLE
[AlertIcon] typescript error

### ISSUE THREAD

**Issue by BooYeu** [gluestack/gluestack-ui#1066]
### Description

typescript error

### Steps to reproduce

![截屏2023-09-12 20 23 20](https://github.com/gluestack/gluestack-ui/assets/16587763/9d6f8882-a5d6-423a-af5c-5345f588d52d)
![截屏2023-09-12 20 23 02](https://github.com/gluestack/gluestack-ui/assets/16587763/8660b754-7729-440e-b430-84529f3194fc)

### gluestack-ui Version

0.1.38

### Platform

- [ ] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [X] Android
- [X] iOS

**Comment by BooYeu** [comment]
![截屏2023-09-12 20 26 04](https://github.com/gluestack/gluestack-ui/assets/16587763/8c145876-77a0-4885-9668-4ccfed0f2f29)
And size prop is an optional props in previous version

**Comment by DavidAmyot** [comment]
+1 Also happens for the variant and space props of **Button** and **HStack** for me.
![image](https://github.com/gluestack/gluestack-ui/assets/60398892/f2a5fbbc-76fb-425a-8253-6ba18d3ee97b)
![image](https://github.com/gluestack/gluestack-ui/assets/60398892/d4c72ea5-e237-4655-b223-7f7ae485ebeb)

**Comment by surajahmed** [comment]
@BooYeu Thanks for reporting this. This issue is fixed in the latest version.
Can you please try updating `@gluestack-ui/themed` and `@gluestack-style/react` to the latest?

**Comment by dg0005** [comment]
> @BooYeu Thanks for reporting this. This issue is fixed in the latest version. Can you please try updating `@gluestack-ui/themed` and `@gluestack-style/react` to the latest?

Hi @BooYeu  This issue still persist even after updating to latest version.

**Comment by dg0005** [comment]
**### **Please note that this bug is mark open!!****

**Comment by Viraj-10** [comment]
Hey @dg0005, It's working for me. Can you provide repo where issue exist?

**Comment by dg0005** [comment]
<img width="716" alt="Screenshot 2023-12-06 at 3 58 48 PM" src="https://github.com/gluestack/gluestack-ui/assets/112057023/06e38075-6c02-48c9-b760-7d68632eff03">

<img width="539" alt="Screenshot 2023-12-06 at 4 02 01 PM" src="https://github.com/gluestack/gluestack-ui/assets/112057023/34eb80a9-3b51-4aa1-8818-f5c179e274e6">


Hey @Viraj-10, please have a look on below attached screenshot.

**Comment by dg0005** [comment]
> Hey @dg0005, It's working for me. Can you provide repo where issue exi

> <img alt="Screenshot 2023-12-06 at 3 58 48 PM" width="716" src="https://private-user-images.githubusercontent.com/112057023/288375425-06e38075-6c02-48c9-b760-7d68632eff03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyODY3MjYsIm5iZiI6MTcwMjI4NjQyNiwicGF0aCI6Ii8xMTIwNTcwMjMvMjg4Mzc1NDI1LTA2ZTM4MDc1LTZjMDItNDhjOS1iNzYwLTdkNjg2MzJlZmYwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMVQwOTIwMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NGFjZDMwZGM5YWFiNDIzZjQ3M2IzZWM3MjE3NzhhZDQzODY2YmQxMjhkZTdkMjI3NzdiNmM4NGNkNDE2YmVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lQW_WZJlsTkLPH_3gYSpc42hEPviRs1BdkIBAONE0wU"> <img alt="Screenshot 2023-12-06 at 4 02 01 PM" width="539" src="https://private-user-images.githubusercontent.com/112057023/288375665-34eb80a9-3b51-4aa1-8818-f5c179e274e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyODY3MjYsIm5iZiI6MTcwMjI4NjQyNiwicGF0aCI6Ii8xMTIwNTcwMjMvMjg4Mzc1NjY1LTM0ZWI4MGE5LTNiNTEtNGFhMS04ODE4LWY1YzE3OWUyNzRlNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMVQwOTIwMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNTkxMTg2ZjgwYWU4OTk4N2NlNTMxM2JmN2M0ZGU3YThhOTI0YjI5NDFlYjFlZDc4NTdiMjZhZTAwMDQ4Yjk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bH7rjv0ePKXciBxqCyO_p3HOKxxbr7XGLNfN9qLYqfY">
> Hey @Viraj-10, please have a look on below attached screenshot.

Hi @Viraj-10,  by any chance did u go through the above screenshots??
