### ISSUE TITLE
[Actionsheet] the actionsheet shadow is not opacity

### ISSUE THREAD

**Issue by BooYeu** [gluestack/gluestack-ui#1086]
### Description

the shadow opacity is 1 now

### Steps to reproduce

https://github.com/gluestack/gluestack-ui/assets/16587763/5ade290d-a9b1-4f44-8610-d6399ab10c1a

### gluestack-ui Version

0.1.39

### Platform

- [ ] Expo
- [ ] React Native CLI
- [ ] Next
- [X] Web
- [X] Android
- [X] iOS

**Comment by makkarMeenu** [comment]
This is fixed.

**Comment by BooYeu** [comment]
I used the latest version 0.1.44.
But it seems like still not right in ios.

https://github.com/gluestack/gluestack-ui/assets/16587763/fcede457-c712-42e3-a73f-1498e2bcbf6f
