### ISSUE TITLE
Typescript: fill="currentColor" property gives error

### ISSUE THREAD

**Issue by jacargentina** [gluestack/gluestack-ui#1177]
### Description

Typescript: fill="currentColor" property gives error

### Steps to reproduce

```jsx
<RadioIcon as={CircleIcon} fill="currentColor" />
```

<img width="932" alt="Captura de pantalla 2023-09-27 a la(s) 08 45 08" src="https://github.com/gluestack/gluestack-ui/assets/517228/84052bbc-b37e-43e9-8533-0ad54fa37f29">

### gluestack-ui Version

0.1.51

### Platform

- [X] Expo
- [X] React Native CLI
- [X] Next
- [X] Web
- [X] Android
- [X] iOS

**Comment by makkarMeenu** [comment]
We will look into this revert asap.

**Comment by surajahmed** [comment]
@jacargentina This PR https://github.com/gluestack/gluestack-ui-unstyled/pull/75 will fix the typing issue in the coming release.

**Comment by makkarMeenu** [comment]
This has been fixed in the latest version of `@gluestack-ui/themed` i.e. `1.0.16`.

**Comment by jacargentina** [comment]
@makkarMeenu  still having this issue? Should this be re-opened?

<img width="417" alt="Captura de pantalla 2023-12-11 a la(s) 16 04 35" src="https://github.com/gluestack/gluestack-ui/assets/517228/22c66b78-46d2-44ad-a90f-8b220a019b59">


<img width="863" alt="Captura de pantalla 2023-12-11 a la(s) 16 04 51" src="https://github.com/gluestack/gluestack-ui/assets/517228/013f83b8-f4bd-45bf-b8bc-7dd77abf3552">
