### ISSUE TITLE
Typescript Autocompletion on eject theme stopped working

### ISSUE THREAD

**Issue by borstessi** [gluestack/gluestack-ui#1388]
### Description

Autocompletion via typescript stopped working in editor on ejected themes.
If you write any gluestack component imported by e.g. import { Box, Button, ButtonText, Heading, VStack } from "@gluestack-ui/themed";

you dont get any autocompletion on properties.

### Steps to reproduce

Create new typescript expo project.

Install gluestack-ui.

"@gluestack-style/react": "^1.0.16",
    "@gluestack-ui/themed": "^1.0.15",

Eject theme to recieve own config file.

Try to use <Box m and wait for autocompletion... doesnt work :(

![Bildschirmfoto 2023-11-16 um 15 07 32](https://github.com/gluestack/gluestack-ui/assets/17229407/b94c408d-6632-4239-9730-3b868ba6233e)
![Bildschirmfoto 2023-11-16 um 15 07 51](https://github.com/gluestack/gluestack-ui/assets/17229407/8f59c4df-ca92-41f5-b156-f782bb9e1903)
![Bildschirmfoto 2023-11-16 um 15 07 39](https://github.com/gluestack/gluestack-ui/assets/17229407/d9c907ad-ccf3-49d9-9a68-b6ecf9610097)

### gluestack-ui Version

1.0.15

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

**Comment by ankit-tailor** [comment]
Hey @borstessi, Can you share the minimal reproduction of the issue? It's working for me.

**Comment by borstessi** [comment]
Setup new gluestack project
`npm create gluestack`

Install dependencies
`npm i @gluestack-ui/themed @gluestack-style/react react-native-svg@13.4.0`

Eject theme
`npx gluestack-ui-scripts eject-theme`

That's all i need to do. Autocompletion stops working.

Package.json looks like this:

```{
  "name": "expo-app",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@expo/html-elements": "^0.5.1",
    "@gluestack-style/react": "^1.0.16",
    "@gluestack-ui/config": "^1.0.3",
    "@gluestack-ui/themed": "^1.0.16",
    "expo": "^49.0.0",
    "expo-status-bar": "~1.6.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.72.5",
    "react-native-svg": "^13.4.0",
    "react-native-web": "~0.19.6"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@expo/webpack-config": "^19.0.0",
    "@types/react": "~18.2.14",
    "typescript": "^5.1.3"
  },
  "private": true
}
```

I am using webstorm as editor.

**Comment by ankit-tailor** [comment]
@borstessi Please share the repository to help us further reproduce the issue. I followed the same steps and it worked for me.

**Comment by ankit-tailor** [comment]
Thanks @borstessi, I'll look into it.

**Comment by ankit-tailor** [comment]
@borstessi, Upgrade `@gluestack-ui/themed` to the latest version. It should fix the issue. Let me know if it works for you.

**Comment by borstessi** [comment]
@ankit-tailor autocompletion behavior still missing with the latest version.

**Comment by Viraj-10** [comment]
Hey @borstessi, there is problem in your ejected folder there are compiled types present inside config folder. Delete those files with `.d.ts` extension should resolve your issue.
Let me know if it doesn't work.

**Comment by vaniyokk** [comment]
I have the same issue in WebStorm, and doesn't have d.ts in my ejected configuration.

**Comment by borstessi** [comment]
@vaniyokk thanks for commenting again. I was working on another project, so this issue has been forgotten.

@Viraj-10 problem persists for me even after deleting the d.ts files.

**Comment by Simoon-F** [comment]
I ran into the same problem.
