### ISSUE TITLE
Menu placement flickers on opening

### ISSUE THREAD

**Issue by DavidAmyot** [gluestack/gluestack-ui#1463]
### Description

I expect the menu placement to appear where it's supposed to at once instead of appearing at the top-left and then moving to where it's asked to be.

### CodeSandbox/Snack link

https://snack.expo.dev/FyeS6D77L?platform=android

### Steps to reproduce

1. Select the android platform
2. Press "tap to play"
3. Click the menu button

### gluestack-ui Version

latest

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [X] Android
- [ ] iOS

### Additional Information

With the latest version of gluestack, when opening a menu, the menu items appear somewhere else on the screen rapidly before being placed properly instead of just being appearing where the placement prop specifies to.

The codesandbox included shows the behavior.

**Comment by DavidAmyot** [comment]
Additionally, I feel as though there is a very big delay for the **opening** and **closing** of the menu compared to the web version.

**Comment by Gluant101** [comment]
Thanks for reporting this. We'll provide an update soon.

**Comment by RogerDeng** [comment]
Has this issue been resolved?

**Comment by yuriyyakym** [comment]
@RogerDeng not yet, I'm still having it on iOS.

**Comment by RyanClementsHax** [comment]
If it helps, this is visible on this example https://snack.expo.dev/@viraj_10/menu-item-onselection-change?platform=android

**Comment by Viraj-10** [comment]
This issue has been fixed in latest version.
please upgrade to latest versions of `@gluestack-ui/themed@1.1.0`, `@gluestack-ui/config@1.1.0` & `@gluestack-style/react@1.0.41`.

**Comment by DavidAmyot** [comment]
> This issue has been fixed in latest version. please upgrade to latest versions of `@gluestack-ui/themed@1.1.0`, `@gluestack-ui/config@1.1.0` & `@gluestack-style/react@1.0.41`.

I don't believe it is. The issue is still present in our app, and also upgraded to latest versions on the snack and the issue still persists on android: https://snack.expo.dev/@davidamyot/menu-placement-flicker?platform=android

Package versions:
```
"@gluestack-ui/config": "^1.1.1",
"@gluestack-ui/themed": "^1.1.2",
"@gluestack-style/react": "^1.0.44"
```

@Viraj-10 Could you please confirm this? 

Thank you 🙂

**Comment by DavidAmyot** [comment]
@Viraj-10 Actually, it seems as though there was a regression with the latest versions since with the versions you mentioned it works, but not with the latest versions of gluestack.
