### ISSUE TITLE
Difficulty with the Select, Menu and ActionSheet

### ISSUE THREAD

**Issue by Gluant101** [gluestack/gluestack-ui#1591]
### Description

Hey, I've installed gluestack into my react native project and have working versions of a lot of the components, but I'm having difficulty with the Select, Menu and ActionSheet which I'm aware are all marked as beta. I have copied the examples in the docs and but cannot get any of them to open (i.e. dropdown of options to show and menu and actionsheet to open on button press) on either ios or android. Should the beta components be readily available to use in the latest release or is there something I may be missing?

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### gluestack-ui Version

3.3.1

### Platform

- [ ] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

### Additional Information

Versions I am using:
```
"@gluestack-style/react": "^1.0.31",
"@gluestack-ui/config": "^1.0.10",
"@gluestack-ui/themed": "^1.0.33",
```

**Comment by AstaninIvan** [comment]
same problem

**Comment by AstaninIvan** [comment]
Select works fine with prop useRNModal for portal  <Select.Portal useRNModal>

**Comment by vbro1293** [comment]
> Select works fine with prop useRNModal for portal <Select.Portal useRNModal>

@AstaninIvan  Ah thank you - Adding that prop fixed the Select component, also adding `useRNModal` to the ActionSheet worked!

Unfortunately still having issues with the Menu (would be good to get the above included in the docs if possible please)

**Comment by AstaninIvan** [comment]
@vbro1293, i found another solution to the problem. The wrong UI provider was used. I used GluestackUIStyledProvider instead of GluestackUIProvider. GluestackUIProvider uses OverlayProvider internally.  useRNModal is no longer necessary after this change

**Comment by admin-sogitec** [comment]
For Web suport i change Module to .js

![Screenshot 2024-01-19 at 14 39 42](https://github.com/gluestack/gluestack-ui/assets/127779662/d2ba64c4-cb33-4c3f-add6-2c95f04bded0)

**Comment by Viraj-10** [comment]
This issue has been fixed in latest version.
please upgrade to latest versions of `@gluestack-ui/themed@1.1.0`, `@gluestack-ui/config@1.1.0` & `@gluestack-style/react@1.0.41`.

**Comment by vbro1293** [comment]
Thanks @Viraj-10

**Comment by brianGammon** [comment]
> > Select works fine with prop useRNModal for portal <Select.Portal useRNModal>
> 
> @AstaninIvan Ah thank you - Adding that prop fixed the Select component, also adding `useRNModal` to the ActionSheet worked!
> 
> Unfortunately still having issues with the Menu (would be good to get the above prop included in the docs if possible please)

@Viraj-10 I also have noticed that this issue still exists with the Menu component. There does not seem to be a useRNModal prop available on Menu. Should I open a new issue?
