### ISSUE TITLE
Error comes from useToken hook

### ISSUE THREAD

**Issue by Gluant101** [gluestack/gluestack-ui#1629]
### Description

Link: https://discord.com/channels/1050761204852858900/1071008851350016041/1195304957264531567

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### gluestack-ui Version

3.3.1

### Platform

- [ ] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

### Additional Information

hey guys....after upgrading to gluestack-style/react:1.0.37, getting following exception
Cannot read property 'hasOwnProperty' of undefined {}

the error comes from useToken hook, to be more precise, from this line: if (theme.config.themes.hasOwnProperty(currentTheme)) {
can you take a look into it?

**Comment by austin43** [comment]
I found this broke after @gluestack-style/react@1.0.32 specifically.  .31 works just fine.  Hope this helps.

**Comment by gvillena** [comment]
Thank you bro! I was suffering for this.

**Comment by ankit-tailor** [comment]
Hey @Gluant101 @austin43 @gvillena, Thanks for reporting the issue. We'll look into it.

**Comment by ankit-tailor** [comment]
Hi there, The issue is fixed in the latest version of `@gluestack-style/react`. Please upgrade to latest version. Feel free to re-open the issue in case of any queries.

**Comment by tanvirshajahan** [comment]
this issue persist on
    "@gluestack-style/react": "^1.0.57",
