### ISSUE TITLE
Toast not showing on latest versions

### ISSUE THREAD

**Issue by DavidAmyot** [gluestack/gluestack-ui#2083]
### Description

I expect the Toast component to show the toast, but it does not.

### gluestack-ui Version

latest

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

### Additional Information

Could not reproduce on Snack unfortunately. I am unsure if it's because of the expo version which is the latest on my project vs on Snack or if it's because I have expo-router v3 in my project. 

I currently have `@gluestack-ui/config 1.1.18` and `@gluestack-ui/themed 1.1.22` and with those, the **Toast** does not work.

However, after trying out different older branches I had, I found out that with `@gluestack-ui/config 1.1.17` and `@gluestack-ui/themed 1.1.12`, the Toast appears fine so I'm guessing the issue comes from one of the two.

![image](https://github.com/gluestack/gluestack-ui/assets/60398892/365f549e-2216-4bb9-b28f-a23fbf284e83)

I am on the latest version of expo and expo-router, expo-doctor runs fine with no issues found.

Thanks for the help.

**Comment by surajahmed** [comment]
@DavidAmyot Thanks fore reporting this. We'll have a look.

**Comment by msschwartz** [comment]
@surajahmed any update on this?

**Comment by JavanPoirier** [comment]
+1 👀

**Comment by Rossella-Mascia-Neosyn** [comment]
i have the same problem with react native cli

**Comment by Viraj-10** [comment]
Hey @JavanPoirier @Rossella-Mascia-Neosyn @msschwartz @DavidAmyot, 

Currently our portal is based on context due to this it render behind `expo-router`. We are working towards a solid solution which will resolve this issues.  We are working on improved version of toast which will take advantage of packages like `react-native-z-view` or native api's.

**Comment by evelant** [comment]
@Viraj-10 Any thoughts on how to solve this one? I'm running into this. Also running into a situation where if I try to use `useToast` inside of a gluestackv2 modal it crashes because the ToastContext is unavailable.

**Comment by YukiOmori** [comment]
I've just solved this problem by just `rm yarn.lock` and `yarn install` .
But I'm not sure why this works.

My versions are below.

```package.json
"@gluestack-style/react": "^1.0.22",
"@gluestack-ui/config": "^1.0.5",
"@gluestack-ui/themed": "^1.0.20",
```

I hope this will help.

**Comment by villemuittari** [comment]
Using @gluestack-ui/config 1.1.17 and @gluestack-ui/themed 1.1.12 Toast works like defined in documentation.

**Comment by sra1kumar-NULL** [comment]
Hey @evelant @msschwartz @villemuittari @YukiOmori , Please use the latest versions of the packages always that should fix the minor issues you are facing. Closing this issue for now, please feel free to open this issue on any issues/ queries related to this context.

**Comment by acv-dancom** [comment]
Hey, still not working on gluestack v2, any idea? I have all the dependencies updated

**Comment by Aszurar** [comment]
still not working on gluestack v2

Expo, Nativewind and  Gluestack UI but the toast component not showed:

![Image](https://github.com/user-attachments/assets/b8dac384-0161-480a-aa5b-9feb511c026a)
