### ISSUE TITLE
Icons that require `fill` don't change color on native

### ISSUE THREAD

**Issue by aaronatbissell** [gluestack/gluestack-ui#2385]
### Description

When using a custom SVG `Icon` component that requires `fill`, changing that icon color using `className='text-primary-500'` doesn't work on native

### CodeSandbox/Snack link

https://github.com/aaronatbissell/gluestack-issue-repro

### Steps to reproduce

1. Go to https://github.com/aaronatbissell/gluestack-issue-repro
2. npm install
3. npm run ios
4. See the first icon doesn't change color

Code for the CheckIcon that needs to be filled:

```js
const CheckIcon2 = createIcon({
  Root: Svg,
  viewBox: '0 0 448 512',
  path: (
    <>
    <Path
    d="M440.1 103C450.3 112.4 450.3 127.6 440.1 136.1L176.1 400.1C167.6 410.3 152.4 410.3 143 400.1L7.029 264.1C-2.343 255.6-2.343 240.4 7.029 231C16.4 221.7 31.6 221.7 40.97 231L160 350.1L407 103C416.4 93.66 431.6 93.66 440.1 103V103z"
    fill='currentColor'
    />
    </>
  ),
});
CheckIcon2.displayName = "CheckIcon2";
export {CheckIcon2};
```

```js
<View style={{flex: 1}}>
  {/* Check Icon that needs to be "filled" */}
  <Icon as={CheckIcon2} size='xl' className='text-tertiary-500' />
  <Icon as={CheckIcon2} size='xl' className='text-primary-500' />
  <Icon as={CheckIcon2} size='xl' className='text-secondary-500' />
  <Icon as={CheckIcon2} size='xl' className='text-typography-950' />
</View>
{/* Gluestack Check Icon (only needs `stroke`) */}
<View style={{flex: 1}}>
  <Icon as={CheckIcon} size='xl' className='text-tertiary-500' />
  <Icon as={CheckIcon} size='xl' className='text-primary-500' />
  <Icon as={CheckIcon} size='xl' className='text-secondary-500' />
  <Icon as={CheckIcon} size='xl' className='text-typography-950' />
</View>
```
<img src="https://github.com/user-attachments/assets/5aecfce2-06de-4696-be60-439d917bfeff" width="200">

### gluestack-ui Version

@gluestack-ui/icon: "0.1.22"

### Platform

- [X] Expo
- [X] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

**Comment by aaronatbissell** [comment]
Just another observation, if I set the `fillColor` on the `Path` of the `SVG` to something like `red`, then it displays correctly in red:

```js
const CheckIcon2 = createIcon({
  Root: Svg,
  viewBox: '0 0 448 512',
  path: (
    <>
    <Path
    d="M440.1 103C450.3 112.4 450.3 127.6 440.1 136.1L176.1 400.1C167.6 410.3 152.4 410.3 143 400.1L7.029 264.1C-2.343 255.6-2.343 240.4 7.029 231C16.4 221.7 31.6 221.7 40.97 231L160 350.1L407 103C416.4 93.66 431.6 93.66 440.1 103V103z"
    fill='red' // <-- set this to `red` instead of `currentColor`
    />
    </>
  ),
});
CheckIcon2.displayName = "CheckIcon2";
export {CheckIcon2};
```
<img src="https://github.com/user-attachments/assets/d5959691-66f4-4174-a034-023ed21e891e" width="300">

**Comment by aaronatbissell** [comment]
Even the example on the bottom of the [Icon docs](https://gluestack.io/ui/docs/components/icon) doesn't appear to be working

```js
const GluestackIcon = createIcon({
    // createIcon function is imported from '@gluestack-ui/themed'
    viewBox: "0 0 32 32",
    path: (
      <>
        {/* Rect, Path is imported from 'react-native-svg' */}
        <Rect width="32" height="32" rx="2" fill="currentColor" />
        <Path
          d="M9.5 14.6642L15.9999 9.87633V12.1358L9.5 16.9236V14.6642Z"
          fill="white"
        />
        <Path
          d="M22.5 14.6642L16.0001 9.87639V12.1359L22.5 16.9237V14.6642Z"
          fill="white"
        />
        <Path
          d="M9.5 19.8641L15.9999 15.0763V17.3358L9.5 22.1236V19.8641Z"
          fill="white"
        />
        <Path
          d="M22.5 19.8642L16.0001 15.0764V17.3358L22.5 22.1237V19.8642Z"
          fill="white"
        />
      </>
    ),
  })
```

```js
<Icon as={GluestackIcon} size="xl" className="text-typography-black" />
```

<img src="https://github.com/user-attachments/assets/d1c028f9-0fbb-4103-ae2b-6e0968dbc961" width=300>

**Comment by rajat693** [comment]
The issue has been resolved with the gluestack-ui icons. Please update your `icon` component.
Thank you

**Comment by mnemitz** [comment]
This example from the icon docs still isn't working for me on v0.1.22: 
https://github.com/gluestack/gluestack-ui/issues/2385#issuecomment-2295241878

![Screenshot 2024-09-25 at 12 20 38](https://github.com/user-attachments/assets/eda72c52-a5e7-4260-9fdf-76b0c21afc7d)

```javascript
export const GluestackIcon = createIcon({
  Root: Svg,
  viewBox: "0 0 32 32",
  path: (
    <>
      {/* Rect, Path is imported from 'react-native-svg' */}
      <Rect width="32" height="32" rx="2" fill="currentColor" />
      <Path d="M9.5 14.6642L15.9999 9.87633V12.1358L9.5 16.9236V14.6642Z" fill="white" />
      <Path d="M22.5 14.6642L16.0001 9.87639V12.1359L22.5 16.9237V14.6642Z" fill="white" />
      <Path d="M9.5 19.8641L15.9999 15.0763V17.3358L9.5 22.1236V19.8641Z" fill="white" />
      <Path d="M22.5 19.8642L16.0001 15.0764V17.3358L22.5 22.1237V19.8642Z" fill="white" />
    </>
  ),
});

```

**Comment by aaronatbissell** [comment]
I also had to make changes to my `icon/index.tsx` because I did a `npx gluestack-ui add icon` prior to #2387 getting merged in. If you did the same, then you will need to make the changes in #2387 manually or do the `npx gluestack-ui add icon` again.

**Comment by Viraj-10** [comment]
@aaronatbissell @mnemitz, Thanks for reporting we will have a look.

**Comment by Viraj-10** [comment]
Thanks @mnemitz, We will add a test case for this. Since this is frequently breaking.

**Comment by aaronatbissell** [comment]
> @aaronatbissell @mnemitz, Thanks for reporting we will have a look.

Just FYI - this is working for me now. I'm not sure if it's broken again, but it's working for me.

@mnemitz  - I would double check that the changes in #2387 made it into your `icon/index.tsx`

**Comment by mnemitz** [comment]
@aaronatbissell Just had a quick look and it looks like there are minor differences between the latest `icon/index.tsx` and the one from the change you linked. The main difference I can see is that the `color` prop isn't passed directly to the SVG/ 'as' component (not sure if that causes the issue).

I guess there is an explicit check for `stroke`:
```typescript
    } else if (stroke === "currentColor" && color !== undefined) {
      colorProps = { ...colorProps, stroke: color };
    }

```

Probably want an analogous check for `fill === "currentColor"`.

**Comment by suleyman** [comment]
can you try like this

`'use client';
import React from 'react';
import { createIcon } from "@gluestack-ui/icon";
import { Path, G, Svg } from "react-native-svg";

export const HomeIcon: any = createIcon({
  Root: Svg,
  viewBox: "0 0 21 20",
  path: (
    <>
      <Path
        d="M10.4996 2.18714C8.75669 2.18714 7.05289 2.70399 5.60368 3.67232C4.15447 4.64065 3.02495 6.01697 2.35795 7.62724C1.69096 9.23752 1.51644 11.0094 1.85647 12.7189C2.1965 14.4283 3.03581 15.9986 4.26826 17.231C5.50071 18.4635 7.07095 19.3028 8.78041 19.6428C10.4899 19.9828 12.2618 19.8083 13.872 19.1413C15.4823 18.4743 16.8586 17.3448 17.827 15.8956C18.7953 14.4464 19.3121 12.7426 19.3121 10.9996C19.3094 8.66326 18.3801 6.42335 16.728 4.77128C15.0759 3.1192 12.836 2.18987 10.4996 2.18714ZM10.4996 18.6871C8.9792 18.6871 7.4929 18.2363 6.22869 17.3916C4.96449 16.5469 3.97917 15.3462 3.39732 13.9415C2.81547 12.5368 2.66323 10.9911 2.95985 9.49988C3.25648 8.00866 3.98864 6.63887 5.06376 5.56376C6.13887 4.48864 7.50866 3.75648 8.99988 3.45985C10.4911 3.16323 12.0368 3.31547 13.4415 3.89732C14.8462 4.47917 16.0469 5.46449 16.8916 6.72869C17.7363 7.9929 18.1871 9.4792 18.1871 10.9996C18.1847 13.0377 17.3739 14.9916 15.9328 16.4328C14.4916 17.8739 12.5377 18.6847 10.4996 18.6871ZM4.14714 1.64714L1.14714 4.64714C1.04051 4.7465 0.899475 4.80059 0.753749 4.79802C0.608023 4.79545 0.468984 4.73642 0.365924 4.63336C0.262865 4.5303 0.203831 4.39126 0.20126 4.24553C0.198688 4.09981 0.252781 3.95877 0.352141 3.85214L3.35214 0.852141C3.45877 0.752781 3.59981 0.698688 3.74553 0.70126C3.89126 0.703831 4.0303 0.762865 4.13336 0.865924C4.23642 0.968984 4.29545 1.10802 4.29802 1.25375C4.30059 1.39947 4.2465 1.54051 4.14714 1.64714ZM20.6471 4.64714C20.5417 4.75248 20.3987 4.81165 20.2496 4.81165C20.1006 4.81165 19.9576 4.75248 19.8521 4.64714L16.8521 1.64714C16.7528 1.54051 16.6987 1.39947 16.7013 1.25375C16.7038 1.10802 16.7629 0.968984 16.8659 0.865924C16.969 0.762865 17.108 0.703831 17.2538 0.70126C17.3995 0.698688 17.5405 0.752781 17.6471 0.852141L20.6471 3.85214C20.7525 3.95761 20.8116 4.10058 20.8116 4.24964C20.8116 4.3987 20.7525 4.54167 20.6471 4.64714ZM15.7496 10.4371C15.8988 10.4371 16.0419 10.4964 16.1474 10.6019C16.2529 10.7074 16.3121 10.8505 16.3121 10.9996C16.3121 11.1488 16.2529 11.2919 16.1474 11.3974C16.0419 11.5029 15.8988 11.5621 15.7496 11.5621H10.4996C10.3505 11.5621 10.2074 11.5029 10.1019 11.3974C9.9964 11.2919 9.93714 11.1488 9.93714 10.9996V5.74964C9.93714 5.60046 9.9964 5.45738 10.1019 5.35189C10.2074 5.2464 10.3505 5.18714 10.4996 5.18714C10.6488 5.18714 10.7919 5.2464 10.8974 5.35189C11.0029 5.45738 11.0621 5.60046 11.0621 5.74964V10.4371H15.7496Z"
         />
    </>
  ),
});`

**Comment by suleyman** [comment]
can you try like this

```
'use client';
import React from 'react';
import { createIcon } from "@gluestack-ui/icon";
import { Path, G, Svg } from "react-native-svg";

export const HomeIcon: any = createIcon({
  Root: Svg,
  viewBox: "0 0 21 20",
  path: (
    <>
      <Path
        d="M10.4996 2.18714C8.75669 2.18714 7.05289 2.70399 5.60368 3.67232C4.15447 4.64065 3.02495 6.01697 2.35795 7.62724C1.69096 9.23752 1.51644 11.0094 1.85647 12.7189C2.1965 14.4283 3.03581 15.9986 4.26826 17.231C5.50071 18.4635 7.07095 19.3028 8.78041 19.6428C10.4899 19.9828 12.2618 19.8083 13.872 19.1413C15.4823 18.4743 16.8586 17.3448 17.827 15.8956C18.7953 14.4464 19.3121 12.7426 19.3121 10.9996C19.3094 8.66326 18.3801 6.42335 16.728 4.77128C15.0759 3.1192 12.836 2.18987 10.4996 2.18714ZM10.4996 18.6871C8.9792 18.6871 7.4929 18.2363 6.22869 17.3916C4.96449 16.5469 3.97917 15.3462 3.39732 13.9415C2.81547 12.5368 2.66323 10.9911 2.95985 9.49988C3.25648 8.00866 3.98864 6.63887 5.06376 5.56376C6.13887 4.48864 7.50866 3.75648 8.99988 3.45985C10.4911 3.16323 12.0368 3.31547 13.4415 3.89732C14.8462 4.47917 16.0469 5.46449 16.8916 6.72869C17.7363 7.9929 18.1871 9.4792 18.1871 10.9996C18.1847 13.0377 17.3739 14.9916 15.9328 16.4328C14.4916 17.8739 12.5377 18.6847 10.4996 18.6871ZM4.14714 1.64714L1.14714 4.64714C1.04051 4.7465 0.899475 4.80059 0.753749 4.79802C0.608023 4.79545 0.468984 4.73642 0.365924 4.63336C0.262865 4.5303 0.203831 4.39126 0.20126 4.24553C0.198688 4.09981 0.252781 3.95877 0.352141 3.85214L3.35214 0.852141C3.45877 0.752781 3.59981 0.698688 3.74553 0.70126C3.89126 0.703831 4.0303 0.762865 4.13336 0.865924C4.23642 0.968984 4.29545 1.10802 4.29802 1.25375C4.30059 1.39947 4.2465 1.54051 4.14714 1.64714ZM20.6471 4.64714C20.5417 4.75248 20.3987 4.81165 20.2496 4.81165C20.1006 4.81165 19.9576 4.75248 19.8521 4.64714L16.8521 1.64714C16.7528 1.54051 16.6987 1.39947 16.7013 1.25375C16.7038 1.10802 16.7629 0.968984 16.8659 0.865924C16.969 0.762865 17.108 0.703831 17.2538 0.70126C17.3995 0.698688 17.5405 0.752781 17.6471 0.852141L20.6471 3.85214C20.7525 3.95761 20.8116 4.10058 20.8116 4.24964C20.8116 4.3987 20.7525 4.54167 20.6471 4.64714ZM15.7496 10.4371C15.8988 10.4371 16.0419 10.4964 16.1474 10.6019C16.2529 10.7074 16.3121 10.8505 16.3121 10.9996C16.3121 11.1488 16.2529 11.2919 16.1474 11.3974C16.0419 11.5029 15.8988 11.5621 15.7496 11.5621H10.4996C10.3505 11.5621 10.2074 11.5029 10.1019 11.3974C9.9964 11.2919 9.93714 11.1488 9.93714 10.9996V5.74964C9.93714 5.60046 9.9964 5.45738 10.1019 5.35189C10.2074 5.2464 10.3505 5.18714 10.4996 5.18714C10.6488 5.18714 10.7919 5.2464 10.8974 5.35189C11.0029 5.45738 11.0621 5.60046 11.0621 5.74964V10.4371H15.7496Z"
         />
    </>
  ),
});
```

**Comment by hyeonjun-commit** [comment]
If you want to use fill when creating custom icons with `createIcon()` or using existing icons, try tailwind fill class.
text is stroke color
fill is fill color

<Icon
  as={FavouriteIcon}
  size="md"
  className="fill-red-600 text-blue-900"
/>
`

When creating a path with `createIcon()`, it is specified as "currentColor" when the fill is not explicitly specified

**Comment by Ren-Logronio** [comment]
is a fix still being worked on? its 2025

**Comment by OneHatRepo** [comment]
I was wrestling with this for eight hours today, and eventually created a patched version of createIcon that works on native. You just submit the "fill-*" className and it works with that color.

`<Icon
  as={MyIcon}
  size="md"
  className="fill-white"
/>`

I don't have time to do a pull request, but the relevant code changes are here (modifying **/node_modules/@gluestack-ui/icon/lib/createIcom/index.jsx**):

**Change line 27**
from
`const { stroke = 'currentColor', color, role = 'img', ...resolvedProps } = finalProps;`
to: 
`const { stroke = 'currentColor', fill, color, role = 'img', ...resolvedProps } = finalProps;`

_This gives us access to the fill color._

Change line 51
from
`{React.Children.map(children, (child, i) => (<ChildPath key={child?.key ?? i} element={child} {...child?.props}/>))}`
to
`{React.Children.map(children, (child, i) => (<ChildPath key={child?.key ?? i} element={child} {...child?.props} fill={fill || child?.props?.fill}/>))}`

_This pushes fill down to the child components of Svg._

My understanding is that on web, react-native-svg allows the fill color to be applied to the Svg component, which automatically pushes this color down to children. On native, that doesn't happen, so we have to push the fill color to children manually. 

The way I did this on a single native project was to hijack the "import { createIcon } ..." statement in the **/components/Gluestack/icon/index.tsx** file to point to my modified version of createIcon.

**Comment by onyedikachi23** [comment]
> I was wrestling with this for eight hours today, and eventually created a patched version of createIcon that works on native. You just submit the "fill-*" className and it works with that color.
> 
> `<Icon as={MyIcon} size="md" className="fill-white" />`
> 
> I don't have time to do a pull request, but the relevant code changes are here (modifying **/node_modules/@gluestack-ui/icon/lib/createIcom/index.jsx**):
> 
> **Change line 27** from `const { stroke = 'currentColor', color, role = 'img', ...resolvedProps } = finalProps;` to: `const { stroke = 'currentColor', fill, color, role = 'img', ...resolvedProps } = finalProps;`
> 
> _This gives us access to the fill color._
> 
> Change line 51 from `{React.Children.map(children, (child, i) => (<ChildPath key={child?.key ?? i} element={child} {...child?.props}/>))}` to `{React.Children.map(children, (child, i) => (<ChildPath key={child?.key ?? i} element={child} {...child?.props} fill={fill || child?.props?.fill}/>))}`
> 
> _This pushes fill down to the child components of Svg._
> 
> My understanding is that on web, react-native-svg allows the fill color to be applied to the Svg component, which automatically pushes this color down to children. On native, that doesn't happen, so we have to push the fill color to children manually.
> 
> The way I did this on a single native project was to hijack the "import { createIcon } ..." statement in the **/components/Gluestack/icon/index.tsx** file to point to my modified version of createIcon.

This doesn't seem to work for me. Instead it even breaks other working functionalities.

**Comment by onyedikachi23** [comment]
The problem is the default `fill-none` applied to `iconStyle`. Here:

```ts

const iconStyle = tva({
	// The "fill-none" here
	base: "text-typography-950 fill-none pointer-events-none",
	variants: {
	// variant props
		},
	},
});

```

This is because NativeWind takes the `fill-none` and uses it to overrides your `fill` prop, caused by this:

```ts

cssInterop(
	// In some places (like  in <BadgeIcon />), this is PrimitiveIcon
	UIIcon,
	{
		className: {
			target: "style",
			nativeStyleToProp: {
				height: true,
				width: true,
				fill: true,
				color: "classNameColor",
				stroke: true,
			},
		},
	},
);

```

This `fill-none` causes a style of `{fill: "transparent"}` which overrides the `fill` prop you set, like `<Icon fill="red" />`.

To prove this, try out the below yourself:

```ts
// This icon will render with a red fill color.
<Icon className="fill-red-500" />;

// This icon will not render with a red fill color.
// The prop is being overridden by the default `fill-none`.
<Icon fill="red" />;

// This icon will render with a blue-500 fill color.
// The fill color from the className prop takes precedence over the fill prop.
<Icon className="fill-blue-500" fill="green" />;
```

The fix is to remove the default `fill-none` from the icon style. You have to do this for any GlueStack Icon component you're using like `Icon`, `ButtonIcon`, `BadgeIcon`, and so on, then optionally replace the intended usage with `fill="transparent"` like this:

```tsx

const iconStyle = tva({
	// "fill-none" has been removed here
	base: "text-typography-950 pointer-events-none",
	variants: {
	// variant props
		},
	},
});


 const Icon: React.FC<IconProps> = ({
    size = "md",
	// Opitionally set the default `fill-none` here
    fill = "transparent",
    className,
    ...props
}) => {
    // ... rest of the component logic
return (
			<UIIcon
				{...props}
				fill={fill}
				className={iconStyle({ class: className })}
			/>
		);
};

```

@Viraj-10 @sra1kumar-NULL you might want to look into this.

**Comment by likaci** [comment]
In addition to @onyedikachi23 mod, svg like this got extra stroke and incorrect fill
```jsx
const SVGComponent = (props: SvgProps) => (
  <Svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 24 24"
    fill="currentColor"
    {...props}
  >
    <Path d="m12 2.586 6.207 6.207-1.414 1.414L13 6.414V16h-2V6.414l-3.793 3.793-1.414-1.414zM3 18v-4h2v4a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-4h2v4a3 3 0 0 1-3 3H6a3 3 0 0 1-3-3" />
  </Svg>
);
```

```jsx
{/* svg icon */}
<Share width={64} height={64} color="red" />
<Icon as={Share} className="h-[64] w-[64] text-[#f00]" />

{/* icon in ui/icon */}
<ArrowUpIcon width={64} height={64} color="red" />
<Icon as={ArrowUpIcon} className="h-[64] w-[64] text-[#f00]" />
```

<img width="254" height="80" alt="Image" src="https://github.com/user-attachments/assets/6bfd6884-9204-4f47-9851-6cbc07b38e13" />

## Patch
Apply patch
remove `fill-none` of `ui/icon/index.tsx`, add `fill: 'none'` and `stroke="currentColor"` to the `ArrowUpIcon`

<details>
<summary>Patch</summary>

```patch
diff --git a/node_modules/@gluestack-ui/icon/src/.DS_Store b/node_modules/@gluestack-ui/icon/src/.DS_Store
new file mode 100644
index 0000000..ecbf185
Binary files /dev/null and b/node_modules/@gluestack-ui/icon/src/.DS_Store differ
diff --git a/node_modules/@gluestack-ui/icon/src/createIcon/index.tsx b/node_modules/@gluestack-ui/icon/src/createIcon/index.tsx
index 0cc88b3..0a2f376 100644
--- a/node_modules/@gluestack-ui/icon/src/createIcon/index.tsx
+++ b/node_modules/@gluestack-ui/icon/src/createIcon/index.tsx
@@ -25,6 +25,7 @@ interface CreateIconOptions {
    * Default props automatically passed to the component; overwritable
    */
   defaultProps?: any;
+  fill?:string;
   type?: any;
 }
 
@@ -67,12 +68,7 @@ export function createIcon<IconProps>({
       ...props,
     };
 
-    const {
-      stroke = 'currentColor',
-      color,
-      role = 'img',
-      ...resolvedProps
-    } = finalProps;
+    const { stroke, color, fill, role = 'img', ...resolvedProps } = finalProps;
     let type = resolvedProps.type;
     if (type === undefined) {
       type = 'svg';
@@ -84,6 +80,9 @@ export function createIcon<IconProps>({
     if (stroke) {
       colorProps = { ...colorProps, stroke: stroke };
     }
+    if (fill) {
+      colorProps = {...colorProps, fill: fill};
+    }
 
     let sizeProps = {};
     let sizeStyle = {};
diff --git a/node_modules/@gluestack-ui/icon/src/primitiveIcon/index.tsx b/node_modules/@gluestack-ui/icon/src/primitiveIcon/index.tsx
index 5940b49..a59828b 100644
--- a/node_modules/@gluestack-ui/icon/src/primitiveIcon/index.tsx
+++ b/node_modules/@gluestack-ui/icon/src/primitiveIcon/index.tsx
@@ -28,7 +28,7 @@ export const PrimitiveIcon = React.forwardRef<
       color,
       classNameColor,
       size,
-      stroke = 'currentColor',
+      stroke,
       as: AsComp,
       style,
       ...props
@@ -48,10 +48,11 @@ export const PrimitiveIcon = React.forwardRef<
     if (fill) {
       colorProps = { ...colorProps, fill: fill };
     }
-    if (stroke !== 'currentColor') {
+    if (stroke) {
       colorProps = { ...colorProps, stroke: stroke };
-    } else if (stroke === 'currentColor' && color !== undefined) {
-      colorProps = { ...colorProps, stroke: color };
+    }
+    if (color) {
+      colorProps = { ...colorProps, color: color };
     }
 
     if (AsComp) {
```

</details>

<img width="252" height="77" alt="Image" src="https://github.com/user-attachments/assets/333ac8d0-774c-4217-94ff-6872d92681d2" />


@mnemitz 's gluestack logo should works too
<img width="60" height="57" alt="Image" src="https://github.com/user-attachments/assets/ecb7c23e-6394-479c-b045-ae8f8325ff6e" />

---
@Viraj-10 @sra1kumar-NULL
I think the problem is `createIcon` and `primitiveIcon` applied the stroke regardless of whether the icon actually needs
and `ui/icon/index.tsx` adds an unnecessary `fill-none`, which makes the Share icon hollow.
It would be better to explicitly specify whether a fill or stroke is needed when creating icons, rather than assuming all icons are stroke-only with no fill by default.

**Comment by OneHatRepo** [comment]
@onyedikachi23 I don't know why my solution wasn't working for you. I created a new project today and my createIcon fix works with that one too. However, my solution is simply a temporary workaround, so if you folks can figure out a more permanent solution, that'd be great!

**Comment by onyedikachi23** [comment]
@OneHatRepo I'm thankful for your suggested solution, but I tried it and didn't work at all.

Anyways, I've figured out the exact problem, and which I've explained and given the solution [here](https://github.com/gluestack/gluestack-ui/issues/2385#issuecomment-3177847626). It's a very simple fix that doesn't need modifying files in node_modules, like you suggested.

**Comment by Papazy** [comment]
is this issue already fixed? its October 2025

**Comment by tgmarinho** [comment]
still happening on v3 too.

**Comment by tgmarinho** [comment]
@onyedikachi23 your solution is not working on v3

**Comment by Sanchitv3** [comment]
Thanks for reporting!

This is no longer applicable with the current version of the codebase.

Closing for now, please open a new issue if it still persists 🙌
