### ISSUE TITLE
gluestack\global.css: Bad character escape sequence. (1:13)

### ISSUE THREAD

**Issue by dineshpithiya** [gluestack/gluestack-ui#2522]
### Description

gluestack\global.css: Bad character escape sequence. (1:13)

### CodeSandbox/Snack link

https://github.com/gluestack/gluestack-ui-starter-kits/tree/main/expo-app

### Steps to reproduce

OS :- Windows 10 Pro
```
npx create-expo-app gluestack --template blank
cd gluestack
npx gluestack-ui init
npx gluestack-ui add --all
```

package.json
` "dependencies": {
    "@expo/html-elements": "^0.4.2",
    "@gluestack-ui/accordion": "^1.0.7",
    "@gluestack-ui/actionsheet": "^0.2.45",
    "@gluestack-ui/alert": "^0.1.15",
    "@gluestack-ui/alert-dialog": "^0.1.31",
    "@gluestack-ui/avatar": "^0.1.17",
    "@gluestack-ui/button": "^1.0.7",
    "@gluestack-ui/checkbox": "^0.1.32",
    "@gluestack-ui/divider": "^0.1.9",
    "@gluestack-ui/fab": "^0.1.21",
    "@gluestack-ui/form-control": "^0.1.18",
    "@gluestack-ui/icon": "^0.1.22",
    "@gluestack-ui/image": "^0.1.10",
    "@gluestack-ui/input": "^0.1.31",
    "@gluestack-ui/link": "^0.1.22",
    "@gluestack-ui/menu": "^0.2.36",
    "@gluestack-ui/modal": "^0.1.34",
    "@gluestack-ui/nativewind-utils": "^1.0.25",
    "@gluestack-ui/overlay": "^0.1.15",
    "@gluestack-ui/popover": "^0.1.37",
    "@gluestack-ui/pressable": "^0.1.16",
    "@gluestack-ui/progress": "^0.1.17",
    "@gluestack-ui/radio": "^0.1.33",
    "@gluestack-ui/select": "^0.1.29",
    "@gluestack-ui/slider": "^0.1.25",
    "@gluestack-ui/spinner": "^0.1.14",
    "@gluestack-ui/switch": "^0.1.22",
    "@gluestack-ui/textarea": "^0.1.23",
    "@gluestack-ui/toast": "^1.0.7",
    "@gluestack-ui/tooltip": "^0.1.33",
    "@legendapp/motion": "^2.4.0",
    "babel-plugin-module-resolver": "^5.0.2",
    "expo": "~51.0.28",
    "expo-status-bar": "~1.12.1",
    "nativewind": "4.0.36",
    "react": "18.2.0",
    "react-native": "0.74.5",
    "react-native-reanimated": "^3.16.0",
    "react-native-svg": "^13.4.0",
    "tailwindcss": "^3.4.14",
    "@types/react": "~18.2.79",
    "react-native-web": "~0.19.10",
    "react-dom": "18.2.0",
    "@expo/metro-runtime": "~3.2.3"
  },`

### gluestack-ui Version

0.1.13

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [X] Web
- [ ] Android
- [ ] iOS

### Other Platform

Windows 10 Pro

### Additional Information

[package.json](https://github.com/user-attachments/files/17445646/package.json)

**Comment by sra1kumar-NULL** [comment]
Hey @dineshpithiya , We are already looking into a similar issue which is occuring only on Windows OS and working on it,  you can track the issue here https://github.com/gluestack/gluestack-ui/issues/2494

**Comment by vaibhk20** [comment]
Closing the issue as the concerned issue has been resolved in the latest version of gluestack-ui CLI. Please feel free to reopen this if you face any issue while using it.

**Comment by dineshpithiya** [comment]
> Closing the issue as the concerned issue has been resolved in the latest version of gluestack-ui CLI. Please feel free to reopen this if you face any issue while using it.

@vaibhk20 Thanks for the looking into this but seems issue still as it is like before. find attached package.json file

`Server Error
SyntaxError: my-app\global.css: Bad character escape sequence. (1:13)

> 1 | require('my-app\node_modules\.cache\nativewind\global.css');
    |              ^
Call Stack
<unknown>
global.css
Collapse 1 frame`

[package.json](https://github.com/user-attachments/files/17948787/package.json)
OS:- Windows 10 Pro
Node:- v20.18.0
Expo:- 52.0.11
React Native:- 0.76.3
