### ISSUE TITLE
fontFamily "Almarai" is not a system font and has not been loaded through Font.loadAsync.  - If you intended to use a system font, make sure you typed the name correctly and that it is supported by your device operating system.  - If this is a custom font, be sure to load it with Font.loadAsync.

### ISSUE THREAD

**Issue by Ahmed-Ibrahim-Anter** [gluestack/gluestack-ui#788]
### Description

font family error 

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### gluestack-ui Version

latest

### Platform

- [ ] Android
- [X] Expo
- [ ] iOS
- [ ] Next

### Additional Information

I follow the steps here [https://ui.gluestack.io/docs/advanced/fonts](url) to install @expo-google-fonts/almarai font after I finished every steps  can not use the font  
if I put  fonts: {
        heading: "Almarai",
        body:  "Almarai",
        mono:  "Almarai",
      },
or 
 fonts: {
        heading:  "almarai",
        body:"almarai" ,
        mono: "almarai",
      },
I had this error 
![Screenshot from 2023-07-20 00-01-52](https://github.com/gluestack/gluestack-ui/assets/76538677/def9d81c-9b0b-4ed7-af58-6966c63d5bca)
but if I use  fonts: {
        heading: "Almarai_700Bold",
        body:  "Almarai_400Regular",
       
      }, it works but this is only one font-weight

**Comment by steve-rodri** [comment]
Any update on this?

**Comment by codeferreira** [comment]
Can you share the entire piece of code? Because I imported IBMPlexSans, and can't make the Gluestack to recognize it as a font and the fontWeight

**Comment by lsarni** [comment]
@nam3886 could you share a bit more of your code? I tried it but I'm getting an error `Element type is invalid: expected a string` from the `createStyled`, but it might be that I'm not using it correctly or have it in the wrong file.

Adding `plugins: [new FontResolver()],` to the config file didn't fix the issue. We are experiencing the same issue as @mconte-mwb describes, which means we can't use semibold, bold or italics.

**Comment by mconte-mwb** [comment]
By looking here https://gluestack.io/style/docs/plugins/fonts-plugin I tried to add env variable to my expo project STYLE_FONT_RESOLVER_STRATEGY='expo' since I'm using @expo-google-fonts but I did not find any way to inject this variable, I'm able by prefixing it with EXPO_PUBLIC but is not the variable I want.

Also tried with something like this but if i trie to console.log the style.fontFamily i get like 'Roboto_undefinedundefinedundefined(...undefined number of undefine)undefine.
```
const CustomFontResolver = new FontResolver({
    mapFonts: (style) => {
      if (Platform.OS !== 'web') {
        style.fontFamily =
          style.fontFamily + '-' + style.fontWeight + '-' + style.fontStyle;
        style.fontWeight = undefined;
        style.fontStyle = undefined;
      }
    },
}),
```

**Comment by steve-rodri** [comment]
There used to be a fontConfig option in native-base for this issue. Are there plans to add support for this?

**Comment by DavidAmyot** [comment]
+1, just having the fonts object with the `useFonts` from **expo-font** is not working for me, I have to hardcode the full _fontFamily_ for it to work like suggested [here](https://github.com/gluestack/gluestack-ui/issues/788#issuecomment-1754688907). `plugins: [new FontResolver()],` did not seem to work either for me, using latest version of all **gluestack** packages.

**Comment by fafo** [comment]
+1, same issue with google fonts. 
The resolver seems to build te string "FontName_SizeRegular_Normal", but Normal is not part of the real font name.
Moreover the new fontFamily names doesn't seem to be used by the processor, but it's using the name in the "body" property in config.

**Comment by DavidAmyot** [comment]
@gluestackadmin Is this issue going to be looked into at some point or is it low priority? Thanks 🙂

**Comment by fafo** [comment]
After more debugging I've realized the font resolver puts the resolved font names into the sx property, but sx was already merged into style before. For this reason the font is not loaded correctly.

In fact if I place the resolved  font family in sx, writing my own style, I get get font correctly.
More over if I look ad the styled component code I see this:

// move before returning component from verboseStyled

  // @ts-ignore
  // plugins?.reverse();
  // for (const pluginName in plugins) {
  //   // @ts-ignore
  //   if (plugins[pluginName]?.componentMiddleWare) {
  //     // @ts-ignore
  //     StyledComponent = plugins[pluginName]?.componentMiddleWare({
  //       Component: StyledComponent,
  //       theme,
  //       componentStyleConfig,
  //       ExtendedConfig,
  //     });
  //   }
  // }
  // move before returning component from verboseStyled
  
  This meas that the plugins, as the font plugin, should be called before expanding the sx properties, but for some reason it's done after. 
 
 Since I don't have a clear picture of all the steps involved in rendering these are just a guess, I hope they are useful hints for the maintainers .

**Comment by hristo87** [comment]
Its real pain to add a font to gluestack in a "React Native CLI" project, in fact i could not find a way to do it. Your documentation, does not provide a guide how to achieve it. @Ahmed-Ibrahim-Anter excuse me for using your issue, but i guess its related.

**Comment by atulrpandey** [comment]
We have resolved the issues, and the final round of testing is in progress. We are hoping to release the fixes tomorrow.

**Comment by hristo87** [comment]
@atulrpandey could you please update your documentation with guide how to add font for RN CLI

**Comment by devethan** [comment]
Happy new year everyone!

native-base used to be resolve this issue like this

```
{
  fontConfig: {
    Pretendard: {
      400: {
        normal: 'Pretendard-Regular',
      },
      500: {
        normal: 'Pretendard-Medium',
      },
      600: {
        normal: 'Pretendard-SemiBold',
      },
      700: {
        normal: 'Pretendard-Bold',
      },
    },
  },
  fonts: {
    heading: 'Pretendard',
    body: 'Pretendard',
    mono: 'Pretendard',
  }
}
```

however there's no refer of this way in the gluestack document. 

```
{
  fontWeights: {
      hairline: '100',
      thin: '200',
      light: '300',
      normal: '400',
      medium: '500',
      semibold: '600',
      bold: '700',
      extrabold: '800',
      black: '900',
      extraBlack: '950',
    },
    fonts: {
      heading: 'Pretendard',
      body: 'Pretendard',
      mono: 'Pretendard',
    }
}
```

How do I get the `fontWeight` that I want?

**Comment by steve-rodri** [comment]
Hey @atulrpandey, Has there been any update on this? Would love to have fonts working for an upcoming client meeting this Thursday. Happy new year! Thanks for all the work you guys do.

**Comment by surajahmed** [comment]
@steve-rodri We're still working on it. Hope to fix this in the next release. I'll update you with a workaround if this doesn't work. Thanks for your patience.

**Comment by ankit-tailor** [comment]
Hi Everyone, We have fixed the issue in the latest version. Please upgrade the `@gluestack-style/react` and `@gluestack-ui/themed` to latest version.

Also I have created a [GitHub repo](https://github.com/ankit-tailor/gluestack-expo-font-example) as reference incase any one want to see the usage of `FontResolver` plugin.

Let me know if you still face any issues. Would be happy to assist.

**Comment by mconte-mwb** [comment]
thx @ankit-tailor, updating to `"@gluestack-style/react": "^1.0.41"` and `"@gluestack-ui/themed": "^1.0.36"` solves my issue

**Comment by mconte-mwb** [comment]
@ankit-tailor , sorry to change my previous answer. The be honest the font in the end is working good, even if I get the error seems that robot is applied. 
I'm still getting this error using ExpoGo and running the code locally.
ExpoGo with eas updates works fine
eas build and code local or eas update works fine.

**Comment by steve-rodri** [comment]
Hey @ankit-tailor I used the github repo you created and added two more google fonts. Montserrat and Outfit. It appears that the fonts change when I change the "body" property on the config but not the "heading" property. Here are the files changed:

App.tsx
```ts
import * as Montserrat from "@expo-google-fonts/montserrat";
import * as Outfit from "@expo-google-fonts/outfit";
import omit from "lodash.omit";

const montserrat = omit(Montserrat, ["__metadata__", "useFonts"]);
const outfit = omit(Outfit, ["__metadata__", "useFonts"]);

const Example = () => {
  let [fontsLoaded] = useFonts({
    Almarai_300Light,
    Almarai_400Regular,
    Almarai_700Bold,
    Almarai_800ExtraBold,
    ...montserrat,
    ...outfit,
  });

```

gluestack.config.ts
```ts
import { config } from "@gluestack-ui/config";

import { FontResolver } from "@gluestack-ui/themed";

export const myConfig = {
  ...config,
  tokens: {
    ...config.tokens,
    fonts: {
      heading: "Montserrat",
      body: "Outfit",
      mono: "Montserrat",
    },
  },
  plugins: [new FontResolver()],
};

```

**Comment by steve-rodri** [comment]
> Hey @ankit-tailor I used the github repo you created and added two more google fonts. Montserrat and Outfit. It appears that the fonts change when I change the "body" property on the config but not the "heading" property.
> 
> Here are the gluestack versions:
> 
> ```json
> "@gluestack-style/react": "1.0.43",
> "@gluestack-ui/config": "1.1.1",
> "@gluestack-ui/themed": "1.1.0",
> ```
> 
> Here are the files changed:
> 
> App.tsx
> 
> ```ts
> import * as Montserrat from "@expo-google-fonts/montserrat";
> import * as Outfit from "@expo-google-fonts/outfit";
> import omit from "lodash.omit";
> 
> const montserrat = omit(Montserrat, ["__metadata__", "useFonts"]);
> const outfit = omit(Outfit, ["__metadata__", "useFonts"]);
> 
> const Example = () => {
>   let [fontsLoaded] = useFonts({
>     Almarai_300Light,
>     Almarai_400Regular,
>     Almarai_700Bold,
>     Almarai_800ExtraBold,
>     ...montserrat,
>     ...outfit,
>   });
> ```
> 
> gluestack.config.ts
> 
> ```ts
> import { config } from "@gluestack-ui/config";
> 
> import { FontResolver } from "@gluestack-ui/themed";
> 
> export const myConfig = {
>   ...config,
>   tokens: {
>     ...config.tokens,
>     fonts: {
>       heading: "Montserrat",
>       body: "Outfit",
>       mono: "Montserrat",
>     },
>   },
>   plugins: [new FontResolver()],
> };
> ```

Quick Update on this.. It looks like the font's work on subsequent reloads of the app. When a font is changed in the theme It will sometimes revert back to the system font (at least in expo go on iOS).

**Comment by fafo** [comment]
> Quick Update on this..
> 
> * It looks like the font's work on subsequent reloads of the app. When a font is changed in the theme It will sometimes revert back to the system font (at least in expo go on iOS).
> * I don't think that this works for an ejected theme because I don't get any response on web or iOS. It just loads the system font.
> 
> Hey @ankit-tailor I used the github repo you created and added two more google fonts. Montserrat and Outfit. It appears that the fonts change when I change the "body" property on the config but not the "heading" property.
> 
> Here are the gluestack versions:
> 
> ```json
> "@gluestack-style/react": "1.0.43",
> "@gluestack-ui/config": "1.1.1",
> "@gluestack-ui/themed": "1.1.0",
> ```
> 
> Here are the files changed:
> 
> App.tsx
> 
> ```ts
> import * as Montserrat from "@expo-google-fonts/montserrat";
> import * as Outfit from "@expo-google-fonts/outfit";
> import omit from "lodash.omit";
> 
> const montserrat = omit(Montserrat, ["__metadata__", "useFonts"]);
> const outfit = omit(Outfit, ["__metadata__", "useFonts"]);
> 
> const Example = () => {
>   let [fontsLoaded] = useFonts({
>     Almarai_300Light,
>     Almarai_400Regular,
>     Almarai_700Bold,
>     Almarai_800ExtraBold,
>     ...montserrat,
>     ...outfit,
>   });
> ```
> 
> gluestack.config.ts
> 
> ```ts
> import { config } from "@gluestack-ui/config";
> 
> import { FontResolver } from "@gluestack-ui/themed";
> 
> export const myConfig = {
>   ...config,
>   tokens: {
>     ...config.tokens,
>     fonts: {
>       heading: "Montserrat",
>       body: "Outfit",
>       mono: "Montserrat",
>     },
>   },
>   plugins: [new FontResolver()],
> };
> ```

I confirm I have the same issue with the heading

**Comment by fafo** [comment]
> Quick Update on this..
> 
> * It looks like the font's work on subsequent reloads of the app. When a font is changed in the theme It will sometimes revert back to the system font (at least in expo go on iOS).
> * I don't think that this works for an ejected theme because I don't get any response on web or iOS. It just loads the system font.
> 
> Hey @ankit-tailor I used the github repo you created and added two more google fonts. Montserrat and Outfit. It appears that the fonts change when I change the "body" property on the config but not the "heading" property.
> 
> Here are the gluestack versions:
> 
> ```json
> "@gluestack-style/react": "1.0.43",
> "@gluestack-ui/config": "1.1.1",
> "@gluestack-ui/themed": "1.1.0",
> ```
> 
> Here are the files changed:
> 
> App.tsx
> 
> ```ts
> import * as Montserrat from "@expo-google-fonts/montserrat";
> import * as Outfit from "@expo-google-fonts/outfit";
> import omit from "lodash.omit";
> 
> const montserrat = omit(Montserrat, ["__metadata__", "useFonts"]);
> const outfit = omit(Outfit, ["__metadata__", "useFonts"]);
> 
> const Example = () => {
>   let [fontsLoaded] = useFonts({
>     Almarai_300Light,
>     Almarai_400Regular,
>     Almarai_700Bold,
>     Almarai_800ExtraBold,
>     ...montserrat,
>     ...outfit,
>   });
> ```
> 
> gluestack.config.ts
> 
> ```ts
> import { config } from "@gluestack-ui/config";
> 
> import { FontResolver } from "@gluestack-ui/themed";
> 
> export const myConfig = {
>   ...config,
>   tokens: {
>     ...config.tokens,
>     fonts: {
>       heading: "Montserrat",
>       body: "Outfit",
>       mono: "Montserrat",
>     },
>   },
>   plugins: [new FontResolver()],
> };
> ```
Other strange behavior. If I add don't add FontResolver plugin it resolves the correct font for body only, instead if I add I get random errors "invalid prop type: fontWeight" for Image tags. 
It seems that the context with resolved styles is not properly cleaned

**Comment by moeBabazadeh** [comment]
Hello everyone,

Hope you're all doing well! 

I've been following this font issue and faced similar challenges with the FontResolver plugin. So, I decided to try fixing it myself and good news – it works now!

![image](https://github.com/gluestack/gluestack-ui/assets/57384/4ac5a4c4-a9a9-440f-ad01-2e408549c3ed)


I believe this revised plugin could be beneficial to others facing similar issues. I'm posting it here for anyone who wishes to use it as a standalone plugin. You can easily include it in your plugin array.

Here's my code: 

```ts
import type { IStyled, IStyledPlugin } from '@gluestack-style/react';
import React from 'react';
import { StyleSheet } from 'react-native';

const fontWeights = {
  '100': 'Thin',
  '200': 'ExtraLight',
  '300': 'Light',
  '400': 'Regular',
  '500': 'Medium',
  '600': 'SemiBold',
  '700': 'Bold',
  '800': 'ExtraBold',
  '900': 'Black',
  '950': 'ExtraBlack',
};

interface FontStyles {
  fontFamily: string;
  fontWeight?: keyof typeof fontWeights;
  fontStyle?: 'normal' | 'italic';
}

interface FontPlugin {
  mapFonts?(fontStyle: FontStyles): FontStyles;
}

const STYLE_FONT_RESOLVER_STRATEGY = 'web';

function isExpoStrategy() {
  return !(
    (typeof window !== 'undefined' && //@ts-ignore
      window.next) ||
    process.env.STYLE_FONT_RESOLVER_STRATEGY === STYLE_FONT_RESOLVER_STRATEGY ||
    process.env.REACT_APP_STYLE_FONT_RESOLVER_STRATEGY ===
      STYLE_FONT_RESOLVER_STRATEGY ||
    process.env.STORYBOOK_STYLE_FONT_RESOLVER_STRATEGY ===
      STYLE_FONT_RESOLVER_STRATEGY ||
    process.env.NEXT_PUBLIC_STORYBOOK_STYLE_FONT_RESOLVER_STRATEGY ===
      STYLE_FONT_RESOLVER_STRATEGY
  );
}

export class FontResolver implements IStyledPlugin, FontPlugin {
  name: 'FontHandler';
  styledUtils: IStyled | undefined = {};

  mapFonts(fontStyles: FontStyles): FontStyles {
    if (isExpoStrategy()) {
      let fontFamilyValue = fontStyles.fontFamily
        .replace(/ /g, '')
        .replace(/^\w/, (c: any) => c.toUpperCase());

      if (fontStyles.fontWeight) {
        fontFamilyValue = `${fontFamilyValue}_${fontStyles.fontWeight}`;
        fontFamilyValue = `${fontFamilyValue}${
          fontWeights[fontStyles.fontWeight]
        }`;
      } else {
        fontFamilyValue = `${fontFamilyValue}_400Regular`;
      }

      if (fontStyles.fontStyle === 'italic') {
        fontFamilyValue = `${fontFamilyValue}_Italic`;
      }

      fontStyles.fontFamily = fontFamilyValue;

      return { fontFamily: fontFamilyValue };
    }

    return fontStyles;
  }

  register(styledUtils: any = {}) {
    if (this.styledUtils) {
      this.styledUtils.aliases = {
        ...this.styledUtils?.aliases,
        ...styledUtils?.aliases,
      };

      this.styledUtils.tokens = {
        ...this.styledUtils?.tokens,
        ...styledUtils?.tokens,
      };

      this.styledUtils.ref = styledUtils?.ref;
    }
  }

  constructor({
    styledUtils,
    mapFonts,
  }: { styledUtils?: IStyled; mapFonts?: FontPlugin['mapFonts'] } = {}) {
    this.register(styledUtils);
    this.name = 'FontHandler';
    this.mapFonts = mapFonts || this.mapFonts;
  }

  componentMiddleWare({ Component: InputComponent, extendedConfig: _ }: any) {
    const OutputComponent = React.forwardRef((props: any, ref: any) => {
      const { style, ...restProps } = props;

      if (!Array.isArray(style)) {
        return <InputComponent {...props} ref={ref} />;
      }

      const flattenStyle = StyleSheet.flatten(style);

      const { fontWeight, fontFamily, fontStyle, ...restStyles } = flattenStyle;

      let fontStyles = {};
      if (fontFamily && fontWeight && fontStyle) {
        fontStyles = this.mapFonts({ fontFamily, fontWeight, fontStyle });
      }

      return (
        <InputComponent
          {...restProps}
          ref={ref}
          style={{ ...restStyles, ...fontStyles }}
        />
      );
    });

    return OutputComponent;
  }

  inputMiddleWare(styledObj: any) {
    return [styledObj];
  }
}

```

Looking forward to your feedback and hoping this makes things a bit smoother for everyone!
If everything's good, I can make a PR to officially add it.

Cheers,
Moe

**Comment by ankit-tailor** [comment]
Hey @moeBabazadeh, Thanks for working on the issue. 

Have you tested this on web? I think your code will work on mobile but it'll break on web. Because we inject styles as CSS instead of forwarding it in style object. 

`inputMiddleWare` removes the styles so that we can prevent the css injection for that style. Along with that it stores theme into class variable so that later on we can merge with component props.

I have fixed the issue in the latest version. You can check out this [PR](https://github.com/gluestack/gluestack-ui/pull/1714). Can you please try upgrading to latest version of `@gluestack-style/react`? 

Let me know if that works for you.

**Comment by rcasari1987** [comment]
Hola, @ankit-tailor, he actualizado y probado la solicitud de extracción. Mi proyecto se genera con React Native CLI. Como no uso expo-font, hice algunos cambios en la función mapFont para satisfacer mis necesidades.

```
export function mapFonts(style: FontStyles) {
    let fontFamilyValue = style.fontFamily
      .replace(/ /g, '')
      .replace(/^\w/, (c: any) => c.toUpperCase());

    if (style.fontWeight) {
      fontFamilyValue = `${fontFamilyValue}-${
        fontWeights[style.fontWeight]
      }`;

    } else {
      fontFamilyValue = `${fontFamilyValue}-Regular`;
    }
    if (
      style.fontStyle &&
      style.fontStyle !== 'normal' &&
      typeof style.fontStyle === 'string'
    ) {
      fontFamilyValue = `${fontFamilyValue}Italic`;
    }

    style.fontFamily = fontFamilyValue;

    delete style.fontWeight;
    delete style.fontStyle;
  
}
```

Con estos cambios, las fuentes ahora se aplican correctamente tanto en Android como en iOS. Sin embargo, me encuentro con el siguiente error: 

```
 ERROR  Warning: Failed prop type: Invalid prop `fontWeight` of value `$medium` supplied to `Text`, expected one of ["100","200","300","400","500","600","700","800","900","black","bold","condensed","condensedBold","heavy","light","medium","normal","regular","semibold","thin","ultralight",100,200,300,400,500,600,700,800,900].
Bad object: {
  "color": "#262626",
  "letterSpacing": 0,
  "fontSize": 16,
  "lineHeight": 22,
  "fontWeight": "$medium",
  "fontFamily": "Montserrat-Thin"
}
```

**Comment by zouchatj** [comment]
<img width="307" alt="image" src="https://github.com/gluestack/gluestack-ui/assets/142948824/719ace54-f889-4a90-a968-59741ee6691e">
As you can see in the screen shot it doesn't seem to be working.  Understanding that yes there is a bold font that I have set up for using Lato-Bold but its linked the same way as Lato-Regular which is working as you can see.  If I apply the bold to the Text or use the heading I can see that my custom mapFonts works, it doesn't want to use the font

**Comment by zouchatj** [comment]
I am using the g as a easy indicator in the word Login to check

**Comment by moeBabazadeh** [comment]
Hi @ankit-tailor 

Thanks for the quick reply! Really appreciate your work on the gluestack-ui library.

After testing with the newest version, it seems the issue persists. I'm trying with two different fonts and logging styles directly from the mapFonts function for better debugging.
Interestingly, If you provide all items from `{ fontFamily,  fontWeight, fontStyle}` then it works well but in case you want to use default values it uses the latest component styling instead of default values!

Here is two sample alongside with consol output:

```ts
      <View p={64}>
        <Text
          sx={{
            fontFamily: 'Roboto',
            // fontWeight: '$black',
          }}
        >
          Roboto black
        </Text>

        <Text
          sx={{
            fontFamily: 'Roboto',
            // fontWeight: '$bold',
            fontStyle: 'italic',
          }}
        >
          Roboto bold italic
        </Text>

        <Text
          sx={{
            fontFamily: 'Roboto',
            // fontWeight: '$normal',
            // fontStyle: 'normal',
          }}
        >
          Roboto bold italic
        </Text>

        <Text
          sx={{
            fontFamily: 'Roboto',
            // fontWeight: '$normal',
            fontStyle: 'italic',
          }}
        >
          Roboto italic
        </Text>

        <Text
          sx={{
            fontFamily: 'Roboto',
            fontWeight: '$normal',
            fontStyle: 'normal',
          }}
        >
          Roboto
        </Text>
      </View>

 LOG  {"fontFamily": "Roboto", "fontStyle": "normal", "fontWeight": "400"}
 LOG  {"fontFamily": "Roboto", "fontStyle": "italic", "fontWeight": "400"}
 LOG  {"fontFamily": "Roboto", "fontStyle": "italic", "fontWeight": "400"}
 LOG  {"fontFamily": "Roboto", "fontStyle": "italic", "fontWeight": "400"}
 LOG  {"fontFamily": "Roboto", "fontStyle": "normal", "fontWeight": "400"}
```

```
      <View p={64}>
        <Text
          sx={{
            fontFamily: 'Roboto',
            fontWeight: '$black',
          }}
        >
          Roboto black
        </Text>

        <Text
          sx={{
            fontFamily: 'Roboto',
            // fontWeight: '$bold',
            fontStyle: 'italic',
          }}
        >
          Roboto bold italic
        </Text>

        <Text
          sx={{
            fontFamily: 'Roboto',
            // fontWeight: '$normal',
            // fontStyle: 'normal',
          }}
        >
          Roboto bold italic
        </Text>

        <Text
          sx={{
            fontFamily: 'Roboto',
            // fontWeight: '$normal',
            fontStyle: 'italic',
          }}
        >
          Roboto italic
        </Text>

        <Text
          sx={{
            fontFamily: 'Roboto',
            fontWeight: '$normal',
            fontStyle: 'normal',
          }}
        >
          Roboto
        </Text>
      </View>

 LOG  {"fontFamily": "Roboto", "fontStyle": "normal", "fontWeight": "900"}
 LOG  {"fontFamily": "Roboto", "fontStyle": "italic", "fontWeight": "900"}
 LOG  {"fontFamily": "Roboto", "fontStyle": "italic", "fontWeight": "900"}
 LOG  {"fontFamily": "Roboto", "fontStyle": "italic", "fontWeight": "900"}
 LOG  {"fontFamily": "Roboto", "fontStyle": "normal", "fontWeight": "400"}
```


Also, I'm not quite familiar with what happens under the hood, but I'm struggling to understand why my code would break web support. For the web, I'm returning the component without making any changes! Just adding a plugin without doing anything inside it shouldn't break web support, right?

**Comment by zouchatj** [comment]
Any updates on this by chance?

**Comment by moeBabazadeh** [comment]
AS far as I know, you can use my simplified version of the plugin, and it works well at least for React Native. I believe it should be OK for web too, but I am not sure of it!

Also, I have to mention it seems gluestack is heavily under development and this may not work on future versions!

**Comment by steve-rodri** [comment]
@moeBabazadeh Unfortunately this still doesn't work on web I just tried your solution.

**Comment by moeBabazadeh** [comment]
@steve-rodri 
Thank you for trying out the solution. I'm sorry to hear that it's still not working on the web. Could you please provide more details about the issue you're encountering? It would be helpful if you could provide steps to reproduce the problem or share a sample project where the issue occurs. With more information, I may be able to investigate further and potentially find a solution.

**Comment by zoucha-fnbo** [comment]
+1 so possibly we can get a Gluestack solution, no offense to @moeBabazadeh quick fix that I appreciate, but obviously don't want it to break in the future.

**Comment by diatche** [comment]
> After testing with the newest version, it seems the issue persists. I'm trying with two different fonts and logging styles directly from the mapFonts function for better debugging. Interestingly, If you provide all items from `{ fontFamily, fontWeight, fontStyle}` then it works well but in case you want to use default values it uses the latest component styling instead of default values!

We're experiencing the same behaviour, but are not able to get the fonts to display correctly neither on web nor in native without specifying `{ fontFamily, fontWeight, fontStyle}` on the components. Looking into the `FontResolver` code (/react/src/plugins/font-resolver.tsx), I've found that the shared object `styledConfig` in line 250 is being modified, so that the `fontWeight` takes the value of the `fontWeight` specified on the last `Text` component props!

Our dependencies:

```
    "@gluestack-style/react": "1.0.49",
    "@gluestack-ui/config": "1.1.16",
    "@gluestack-ui/themed": "1.1.9",
    "expo": "49.0.21",
    ...
```

Take the following test app (font loading and providers removed for clarity):

```jsx
const Main = () => (
  <View>
    <Text testID="first" fontWeight="$normal">
      First
    </Text>
    <Text testID="bold" fontWeight="$extrabold">
      Extra Bold
    </Text>
    <Text testID="default">Default</Text>
  </View>
);
```

Our relevant `Text` config:

```js
{
  fontWeight: '$normal',
  fontFamily: '$body',
  fontStyle: 'normal',
  // ...
}
```

Printing `styledConfig` after line 250, yields the following on web (emphasis added):

styledConfig: undefined
&platform=web&dev=true&hot=false&lazy=true:145331 styledConfig: {**fontWeight: '$normal',** fontFamily: '$body', fontStyle: 'normal', variants: {…}}
&platform=web&dev=true&hot=false&lazy=true:145331 styledConfig: {**fontWeight: '$extrabold'**, fontFamily: '$body', fontStyle: 'normal', variants: {…}}
&platform=web&dev=true&hot=false&lazy=true:145331 styledConfig: {**fontWeight: '$extrabold',** fontFamily: '$body', fontStyle: 'normal', variants: {…}}

No logs are printed on native.

Should this happen? I'm not familiar with how Gluestack plugins work so I'm not able to figure this out, but hopefully this info will help someone who does.

Visually, these look like this:

Web:
<img width="98" alt="Screenshot 2024-03-11 at 10 42 34 AM" src="https://github.com/gluestack/gluestack-ui/assets/5573638/f7c7bcfc-39c9-4aed-9241-ba2faf50dd5f">

iOS: 
<img width="90" alt="Screenshot 2024-03-11 at 10 44 19 AM" src="https://github.com/gluestack/gluestack-ui/assets/5573638/4408b19b-2faf-4d6a-9395-7af1654f8eb3">

**Comment by ankit-tailor** [comment]
Hi everyone👋🏻, Sorry for the delay. The issue is fixed in the latest version of `@gluestack-style/react`. Let me know if that works for you. Closing the issue for now. Feel to re-open it incase you face any issues.

**Comment by Ahmed-Ibrahim-Anter** [comment]
@ankit-tailor 

thanks for your response and your efforts but can you provide us with the method that can change the font weight or we should 
  sx={{
          fontWeight: "300",
          fontFamily: "Almarai",
        }}
