### ISSUE TITLE
Select component out of memory error with Typescript

### ISSUE THREAD

**Issue by schmitzc** [gluestack/gluestack-ui#904]
### Description

Out of memory error when running `tsc`

### Steps to reproduce

1. Use the Select component with Typescript
2. Run `tsc --noEmit`

You will get an out of memory error:

```
> tsc --noEmit


<--- Last few GCs --->

[18343:0x148040000]    27106 ms: Mark-sweep 4047.9 (4137.8) -> 4037.3 (4142.8) MB, 843.6 / 0.0 ms  (average mu = 0.467, current mu = 0.027) allocation failure; scavenge might not succeed
[18343:0x148040000]    28571 ms: Mark-sweep 4053.4 (4142.8) -> 4042.7 (4148.0) MB, 1442.7 / 0.0 ms  (average mu = 0.236, current mu = 0.015) allocation failure; scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
```

### gluestack-ui Version

0.1.9 (@gluestack-ui/themed)

### Platform

- [ ] Android
- [X] Expo
- [ ] iOS
- [ ] Next

**Comment by AshwiniKumar007** [comment]
Hey @schmitzc , 
Thanks for reporting. We will check this.

**Comment by ankit-tailor** [comment]
Hey @schmitzc, The Issue is fixed in the latest version. Let me know if it works for you.

**Comment by schmitzc** [comment]
This is fixed for me. Thank you!

**Comment by lhguerra** [comment]
I'm using the latest version (0.1.18) and it still fails in Github Actions

**Comment by suhaotian** [comment]
Still exists, today I migrate nativebase to gluestack-ui, then push code , github actions error: JavaScript heap out of memory,

**Comment by suhaotian** [comment]
@ankit-tailor No idea why have this error when run `tsc --noEmit` in github actions
