### ISSUE TITLE
[ActionSheet] Input in ActionSheet can't automatically scrolled into view

### ISSUE THREAD

**Issue by BooYeu** [gluestack/gluestack-ui#906]
### Description

Input in ActionSheet can't automatically scrolled into view

### Steps to reproduce

The example in docs:

```
function App() {
  const [showActionsheet, setShowActionsheet] = React.useState(false)
  const handleClose = () => setShowActionsheet(!showActionsheet)
  return (
    <>
      <Button onPress={handleClose}>
        <ButtonText>Open</ButtonText>
      </Button>
      <Actionsheet isOpen={showActionsheet} onClose={handleClose}>
        <ActionsheetBackdrop />
        <ActionsheetContent maxHeight="75%">
          <ActionsheetDragIndicatorWrapper>
            <ActionsheetDragIndicator />
          </ActionsheetDragIndicatorWrapper>
          <VStack w="$full" p={20}>
            <HStack justifyContent="center" alignItems="center" space="md">
              <Box
                w={50}
                h="$full"
                px="$2"
                borderWidth={1}
                borderStyle="solid"
                borderColor="$borderLight300"
                rounded="$sm"
              >
                <Image
                  source={{ uri: "https://i.imgur.com/UwTLr26.png" }}
                  flex={1}
                  resizeMode="contain"
                />
              </Box>
              <VStack flex={1}>
                <Text fontWeight="$bold">Mastercard</Text>
                <Text>Card ending in 2345</Text>
              </VStack>
            </HStack>
            <FormControl mt={36}>
              <FormControlLabel>
                <FormControlLabelText>
                  Confirm security code
                </FormControlLabelText>
              </FormControlLabel>
              <Input w="$full">
                <InputIcon>
                  <Icon as={LeadingIcon} ml="$2" />
                </InputIcon>
                <InputField placeholder="CVC/CVV" />
              </Input>
              <Button onPress={handleClose} mt={20}>
                <ButtonText>Pay $1000</ButtonText>
              </Button>
            </FormControl>
          </VStack>
        </ActionsheetContent>
      </Actionsheet>
    </>
  )
}
```

### gluestack-ui Version

0.1.9

### Platform

- [ ] Android
- [ ] Expo
- [X] iOS
- [ ] Next

**Comment by BooYeu** [comment]
Docs Link: https://ui.gluestack.io/docs/components/disclosure/actionsheet
Docs Example Title is: Keyboard handling

**Comment by Viraj-10** [comment]
Hey @BooYeu, Can you check once working fine now.

**Comment by BooYeu** [comment]
@Viraj-10 I updated the version 0.1.38 and the problem still exsit.

https://github.com/gluestack/gluestack-ui/assets/16587763/84228a83-e7d3-4a85-820e-5bd96c73dd62

**Comment by makkarMeenu** [comment]
> @Viraj-10 I updated the version 0.1.38 and the problem still exsit.
> 
>  2023-09-12.19.39.58.mov

We will have a look, thanks for reporting.

**Comment by Viraj-10** [comment]
Hey @BooYeu, This issue is fixed in latest version of `@gluestack-ui/themed`.

**Comment by IsaacHatilima** [comment]
This issue is still present. the paragraph in the docs under **Keyboard handling** is not very helpful.
